#### Comparison of plain Python lists vs NumPy arrays for element-wise operations.

##### 1. Element-wise Addition: List vs NumPy

In [15]:
import time
import numpy as np

In [16]:
# Plain Python list addition using zip
a = [1, 2, 3, 4, 5]
b = [1, 2, 3, 4, 5]

start = time.time()
c = [a + b for a, b in zip(a, b)]
end = time.time()

print('Result:', c)
print(f'Time taken: {end - start:.8f} seconds')

Result: [2, 4, 6, 8, 10]
Time taken: 0.00008655 seconds


In [17]:
# NumPy array addition — faster and cleaner
x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 2, 3, 4, 5])

start = time.time()
z = x + y
end = time.time()

print('Result:', z)
print(f'Time taken: {end - start:.8f} seconds')

Result: [ 2  4  6  8 10]
Time taken: 0.00007105 seconds


##### 2. Squaring Elements: List vs NumPy

In [18]:
# List comprehension needed for element-wise square
print('List:', [x * x for x in a])

# NumPy applies the operation directly — no loop needed
print('NumPy:', x ** 2)
print('NumPy:', x+10)       #broadcasting

arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])
result = arr1 + arr2 
print(result)  

arr1 = np.array([[1, 2, 3],[4 ,5 ,6]])
result = arr1 + arr2  
print(result) 

List: [1, 4, 9, 16, 25]
NumPy: [ 1  4  9 16 25]
NumPy: [11 12 13 14 15]
[11 22 33]
[[11 22 33]
 [14 25 36]]


##### 3. Array Creation Utilities

In [19]:
print('zeros:   ', np.zeros((2, 3)))
print('ones:    ', np.ones((2, 2)))
print('full:    ', np.full((2, 3), 7))
print('arange (step=2):', np.arange(1, 10, 2))
print('arange (0-2):   ', np.arange(3))
print('linspace:       ', np.linspace(0, 10, num=5))

zeros:    [[0. 0. 0.]
 [0. 0. 0.]]
ones:     [[1. 1.]
 [1. 1.]]
full:     [[7 7 7]
 [7 7 7]]
arange (step=2): [1 3 5 7 9]
arange (0-2):    [0 1 2]
linspace:        [ 0.   2.5  5.   7.5 10. ]
