#### NumPy Arrays — Shape, Reshape & Slicing

##### 1. Array Attributes

In [1]:
import numpy as np

In [9]:
myarray = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12]])

print('Array:\n', myarray)
print('size  :', myarray.size)   # total elements
print('shape :', myarray.shape)  # (rows, cols)
print('ndim  :', myarray.ndim)   # number of dimensions
print('Element at [2,1]:', myarray[2, 1])

Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
size  : 12
shape : (4, 3)
ndim  : 2
Element at [2,1]: 8


##### 2. Reshape and Flatten

In [11]:
reshaped = myarray.reshape((2, 6))
print('Reshaped (2x6):\n', reshaped)

flat = myarray.flatten()
print('Flattened:', flat)

Reshaped (2x6):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Flattened: [ 1  2  3  4  5  6  7  8  9 10 11 12]


##### 3. Slicing — List vs NumPy

###### 3a. Plain Python List Slicing

In [4]:
arr = [10, 20, 30, 40, 50, 60]

print(arr[1:4])   # [20, 30, 40]  — index 1 up to (not including) 4
print(arr[:3])    # [10, 20, 30]  — beginning up to index 3
print(arr[::2])   # [10, 30, 50]  — every other element (step=2)

[20, 30, 40]
[10, 20, 30]
[10, 30, 50]


###### 3b. NumPy Slicing — Creates a *View*, Not a Copy

In [5]:
num_arr = np.array([1, 2, 3, 4, 5])
my_view = num_arr[1:4]   # slice = view into original

my_view[0] = 99          # modifying the view changes the original!
print('Original after modifying view:', num_arr)  # [1, 99, 3, 4, 5]

Original after modifying view: [ 1 99  3  4  5]


###### 3c. Use `.copy()` to Avoid Mutating the Original

In [6]:
num_arr = np.array([1, 2, 3, 4, 5])
my_copy = num_arr[1:4].copy()   # independent copy

my_copy[0] = 99
print('Original (unchanged):', num_arr)   # [1, 2, 3, 4, 5]
print('Copy (modified):     ', my_copy)   # [99, 3, 4]

Original (unchanged): [1 2 3 4 5]
Copy (modified):      [99  3  4]


###### 3d. More NumPy Slice Examples

In [7]:
np_arr = np.array([10, 20, 30, 40, 50, 60])

print(np_arr[1:4])   # [20 30 40] — same syntax as lists
print(np_arr[:3])    # [10 20 30]
print(np_arr[::2])   # [10 30 50] — step slicing

# 2-D slicing
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(mat[0:2, 1:3])   # rows 0-1, cols 1-2  →  [[2,3],[5,6]]
print(mat[:, 1])       # entire second column →  [2, 5, 8]

[20 30 40]
[10 20 30]
[10 30 50]
[[2 3]
 [5 6]]
[2 5 8]
