##### MULTIDIMENSIONAL INDEXING AND AXIS

In [12]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr[0]

array([1, 2, 3])

In [ ]:
print(np.sum(arr,axis=0))       # axis=0 means rows
print(np.sum(arr,axis=1))       # axis=1 means column 

[12 15 18]
[ 6 15 24]


In [26]:
print(arr[0][1])        #as in list
print(arr[0,1])         #in numpy
print(arr[0:2][1:3])    # Slices rows 0 to 1, then takes index 1 of those rows (doesn't touch columns). as in list
print(arr[0:2, 1:3])    # Grabs rows 0 to 1, and simultaneously grabs columns 1 to 2 from them.         in numpy

2
2
[[4 5 6]]
[[2 3]
 [5 6]]
