In [2]:
import numpy as np

In [ ]:
arr = np.array([23, 4,3,23 ])

array([23,  4,  3, 23])

In [4]:
arr.dtype

dtype('int64')

In [5]:
arr.astype("float64")

array([23.,  4.,  3., 23.])

In [6]:
arr2 = np.array([23, 4,3,23 ], dtype="float32")

In [12]:
arr2

array([23.,  4.,  3., 23.], dtype=float32)

In [8]:
arr2.nbytes

16

In [9]:
arr.nbytes

32

In [14]:
arr_int64 = np.array([1, 2, 3], dtype=np.int64)
arr_int32 = np.array([1, 2, 3], dtype=np.int32)
print(arr_int64.nbytes) # Output: 24 bytes (3 elements * 8 bytes each)
print(arr_int32.nbytes) 

24
12


In [15]:
arr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex128')
print(arr)

[1.+2.j 3.+4.j 5.+6.j]


In [ ]:
arr = np.array([{'a': 1}, [1, 2, 3], 'hello'], dtype=object)
print(arr)